packages:
  - 'packages/*'

catalog:
  "@typescript-eslint/eslint-plugin": "^7.14.1"
  "@types/eslint": "^8.56.2"
  "@types/node": "^18.19.7"
  "@types/pacote": "^11.1.8"
  "@types/semver": "^7.5.8"
  "@types/yargs": "^17.0.32"
  "@typescript-eslint/parser": "^7.14.1"
  "@typescript-eslint/types": "^7.14.1"
  "@typescript-eslint/typescript-estree": "^7.14.1"
  "@typescript-eslint/utils": "^7.14.1"
  "semver": "^7.5.4"
  eslint-plugin-jsdoc: '^48.5.2'
  eslint: '^8.40.0'
  glob: "^10.3.10"
  pacote: "^17.0.5"
  typescript: '^5.5.3'
  yargs: "^17.7.2"
