import { DefaultAzureCredential } from "@azure/identity";
import { SecretClient } from "@azure/keyvault-secrets";
import { assertDefined, mapDefined } from "@definitelytyped/utils";
import { azureKeyvault } from "./settings";

export enum Secret {
  /**
   * Lets the server update an issue (https://github.com/Microsoft/types-publisher/issues/40) on GitHub in case of an error.
   * Create a token at: https://github.com/settings/tokens
   */
  GITHUB_ACCESS_TOKEN,
  /**
   * Token used to perform request to NPM's API.
   * This was generated by doing:
   * - `npm login`
   * - copy the token value (comes after `authToken=`) in `~/.npmrc`
   * - `rm ~/.npmrc` (don't want to accidentally log out this token.)
   *
   * We only need one token in existence, so delete old tokens at: https://www.npmjs.com/settings/tokens
   */
  NPM_TOKEN,
}

export const allSecrets: Secret[] = mapDefined(Object.keys(Secret), key => {
  const value = ((Secret as unknown) as { [key: string]: unknown })[key];
  return typeof value === "number" ? value : undefined; // tslint:disable-line strict-type-predicates (tslint bug)
});

export async function getSecret(secretId: Secret): Promise<string> {
  const clientId = process.env.AZURE_CLIENT_ID;
  const clientSecret = process.env.AZURE_CLIENT_SECRET;
  const tenantId = process.env.AZURE_TENANT_ID;
  if (!(clientId && clientSecret && tenantId)) {
    throw new Error("Must set the AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, and AZURE_TENANT_ID environment variables.");
  }

  const credential = new DefaultAzureCredential();
  const client = new SecretClient(azureKeyvault, credential);

  // Convert `AZURE_STORAGE_ACCESS_KEY` to `azure-storage-access-key` -- for some reason, Azure wouldn't allow secret names with underscores.
  const azureSecretName = Secret[secretId].toLowerCase().replace(/_/g, "-");
  const secret = await client.getSecret(azureSecretName);
  return assertDefined(secret.value);
}
