name: Daily Open PR Sync

on:
  workflow_dispatch: ~
  schedule:
    - cron: '37 */6 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: azure
      deployment: false

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - run: pnpm install
      - run: pnpm run build
      - uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - run: node packages/mergebot/dist/run.js
        env:
          GITHUB_APP_CLIENT_ID: ${{ vars.TYPESCRIPT_AUTOMATION_GITHUB_APP_CLIENT_ID }}
          GITHUB_APP_KEY_VAULT_KEY_ID: ${{ vars.TYPESCRIPT_AUTOMATION_GITHUB_APP_KEY_ID }}
