name: Deploy mergebot to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)
  RESOURCE_GROUP_NAME: dtmergebot3
  FUNCTION_APP_NAME: dtmergebot3
  STORAGE_ACCOUNT_NAME: dtmergebot3b1b7
  STORAGE_CONTAINER_NAME: deployment
  FUNCTION_ZIP_NAME: function.zip

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

      - name: Install and test
        run: |
          pnpm install
          pnpm run --if-present build
          pnpm run --if-present test
      - name: Bundle
        working-directory: packages/mergebot
        run: pnpm run bundle

      - name: Check bundle
        run: BOT_AUTH_TOKEN=secret node packages/mergebot/dist/functions/index.js

      - name: Create zip
        working-directory: packages/mergebot
        run: zip -r ${{ github.workspace }}/${{ env.FUNCTION_ZIP_NAME }} dist host.json package.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: node-app
          path: ${{ env.FUNCTION_ZIP_NAME }}

  deploy:
    runs-on:
      - "self-hosted"
      - "1ES.Pool=TypeScript-1ES-GitHub-Deploys"
      - "1ES.ImageOverride=azure-linux-3"
    needs: build
    environment:
      name: 'Production'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: node-app

      - uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Upload blob
        run: az storage blob upload -f ${{ env.FUNCTION_ZIP_NAME }} --account-name ${{ env.STORAGE_ACCOUNT_NAME }} -c ${{ env.STORAGE_CONTAINER_NAME }} -n ${{ env.FUNCTION_ZIP_NAME }} --overwrite true --auth-mode login

      # - name: Set package path
      #   run: az functionapp config appsettings set -g ${{ env.RESOURCE_GROUP_NAME }} -n ${{ env.FUNCTION_APP_NAME }} --settings WEBSITE_RUN_FROM_PACKAGE="https://${{ env.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ env.STORAGE_CONTAINER_NAME }}/${{ env.FUNCTION_ZIP_NAME }}"

      - name: Restart app
        run: az functionapp restart -g ${{ env.RESOURCE_GROUP_NAME }} -n ${{ env.FUNCTION_APP_NAME }}
