name: Publish registry
on:
  schedule:
    # https://crontab.guru/#0_0_*_*_0
    - cron: 0 0 * * 0
  workflow_dispatch:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

concurrency: publish-packages

jobs:
  publish-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ./cache
          key: pacote-cache-${{ github.run_id }}-${{ github.run_attempt}}
          restore-keys: pacote-cache-
      - name: Publish registry
        run: pnpm run --filter @definitelytyped/publisher publish-registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_RETAG_TOKEN }}
      - if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: packages/definitions-parser/data/
      - uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: always()
        with:
          path: ./cache
          key: pacote-cache-${{ github.run_id }}-${{ github.run_attempt}}
