name: Publish registry
on:
  schedule:
    # https://crontab.guru/#0_0_*_*_0
    - cron: 0 0 * * 0
  workflow_dispatch:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

concurrency: publish-packages

jobs:
  publish-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
      - run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ./cache
          key: pacote-cache-${{ github.run_id }}-${{ github.run_attempt}}
          restore-keys: pacote-cache-
      - name: Publish registry
        run: pnpm run --filter @definitelytyped/publisher publish-registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_RETAG_TOKEN }}
      - if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: packages/definitions-parser/data/
      - uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        if: always()
        with:
          path: ./cache
          key: pacote-cache-${{ github.run_id }}-${{ github.run_attempt}}
